<link rel="stylesheet" href="teachingstyles.css" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Quintessential|Merienda|Handlee|Courgette|Kaushan+Script|Tangerine:400,700|Dancing+Script:400,700|Cookie' rel='stylesheet' type='text/css'>
<link rel="icon" href="images/shark-favicon-32x32.png" type="image/x-icon">
<link rel="shortcut icon" href="images/shark-favicon-32x32.png" type="image/x-icon">
<script type="text/javascript" language="JavaScript"><!--
function HideContent(d) {
document.getElementById(d).style.display = "none";
}
function ShowContent(d) {
document.getElementById(d).style.display = "block";
}
function ReverseDisplay(d) {
if(document.getElementById(d).style.display == "none") { document.getElementById(d).style.display = "block"; }
else { document.getElementById(d).style.display = "none"; }
}
//-->
</script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
</head>

<body id="toplevel">
<div id="headerwrapper">
  <div id="headertitle" class="headertitleroundshadow column">
 
		<span class="xxlarge title script">Ms. Claypool</span>
		<br>
		<span class="xlarge title script">Middle School Mathematics</span>
  </div>
  <div id="headerpic" class="column none">
  <a href="http://southbayschool.org" class="none"><img class="logo" src="/images/fluid_shark_white.png" valign="bottom" alt="South Bay School logo"></a>
  </div>
</div>
<div id="spacer">&nbsp;</div>