<hr><span class="script medium">Links</span>
<br> <a href="https://www.desmos.com/calculator" target="_blank">Desmos Graphing Calculator</a>
<br> <a href="https://southbay.schoolwise.com" target="_top">SchoolWise</a>
<br><a href="http://www.southbayschool.org/" target="_blank">South Bay School</a>
<br> <a href="http://www.southbayschool.org/documents/2015-16%20School%20Calendar.pdf" target="_blank">South Bay School Calendar</a>
<hr><span class="script medium">Math Help</span>
<br><a href="http://www.khanacademy.org/" target="_blank">Khan Academy</a>
<br><a href="http://www.brightstorm.com" target="_blank">Brightstorm</a>
<br><a href="http://www.watchknow.org/Category.aspx?CategoryID=81" target="_blank">WatchKnow Videos</a>
<br><a href="http://www.mathtv.com/" target="_blank">Math TV</a>
<br><a href="http://mathforum.org/students/" target="_blank">Math Forum</a>
<br><a href="http://mathworld.wolfram.com/" target="_blank">Wolfram MathWorld</a>
<hr>
<span class="script medium">Math Fun</span>
<br> <a href="http://labyrinth.thinkport.org/www/">Lure of the Labyrinth Game</a>
<br> <a href="https://www.mathcounts.org/resources/problem-of-the-week" target="_blank">MathCounts Problem of the Week</a>
<br> <a href="https://nrich.maths.org/weekly" target="_blank">NRICH Problem of the Week</a>
<br> <a href="http://cemc.uwaterloo.ca/resources/potw.php" target="_blank">U of Waterloo Problems of the Week</a>
<hr>
<span class="script medium">Files</span>
<br> <a href="/resources/2015-12-10_Parent_Letter.pdf" target="_blank">Parent Letter</a>
<br> <a href="/resources/6_Graphs.pdf" target="_blank">6 Graph Paper</a>
<br> <a href="../resources/IsometricDrawingScratch.pdf" target="_blank">Isometric Drawing Paper</a>
<br> <a href="/resources/Greek_Alphabet.pdf" target="_blank">Greek Alphabet :)</a>
<hr>
<span class="script medium">Resources</span>
<br> <a href="http://incompetech.com/graphpaper/" target="_blank">Free Graph Paper</a>
<br> <span class="small">Design & download graph paper</span>
<br> <a href="http://www.mathematicshelpcentral.com/graph_paper.htm" target="_blank">More Free Graph Paper</a>
<br> <span class="small">Graph paper downloads</span>
<br> <a href="http://www.softsea.com/review/Graph-Paper-Printer.html" target="_blank">Graph Paper Printer</a>
<br> <span class="small">Windows app</span>
<br> <a href="http://www.electricsheep.org" target="_blank">Electric Sheep</a>
<br> <span class="small">Best. Screensaver. Ever.</span>
<hr><span class="script medium">Contact Info</span>
<br>Email: 
<br><a href="mailto:margaret.claypool@gmail.com">margaret.claypool@gmail.com</a>
<!--<br><br>Voice mail:
<br>
<a href="javascript:ReverseDisplay('googlevoice')">
Leave me a voice mail</a>
<div id="googlevoice" style="display:none;">
<object type="application/x-shockwave-flash" data="https://clients4.google.com/voice/embed/webCallButton" width="230" height="85"><param name="movie" value="https://clients4.google.com/voice/embed/webCallButton" /><param name="wmode" value="transparent" /><param name="FlashVars" value="id=b54d4a37335d4cf5854afacd763a32b62d4b0101&style=0" /></object>
</div>
-->